name: Rewards Action.
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r modules.txt
      - name: Run Python script and save output to coupon.txt
        run: python udemy.py > coupon.txt
      - name: Collect logs
        uses: actions/upload-artifact@v3
        with:
           name: coupon
           path: coupon.txt
      - name: upload to tele via api
        continue-on-error: true
        run: |
         curl -F document=@coupon.txt -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument
